# Generated by Django 4.2.6 on 2023-11-10 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0003_remove_food_category_delete_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_grams', models.PositiveIntegerField(default=0)),
                ('carbs_grams', models.PositiveIntegerField(default=0)),
                ('fat_grams', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
