# Generated by Django 4.2.6 on 2023-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userauthtoken_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='height_in_inches',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='starting_weight_pounds',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
