# Generated by Django 4.2.6 on 2023-10-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('workout_type', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('weight_training', 'Weight Training'), ('eliptical', 'Eliptical'), ('other', 'Other')], max_length=36)),
                ('duration', models.DurationField(null=True)),
                ('distance_miles', models.PositiveIntegerField(null=True)),
                ('calories_burned', models.PositiveIntegerField()),
                ('avg_heart_rate', models.PositiveIntegerField(null=True)),
                ('max_heart_rate', models.PositiveIntegerField(null=True)),
                ('start_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
