# Generated by Django 4.2.6 on 2023-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('weight_training', 'Weight Training'), ('eliptical', 'Eliptical'), ('other', 'Other')], default='other', max_length=36),
        ),
    ]
